-- Déjà appliqué sur le projet Supabase HorseProno.
-- Table service-role only : RLS activé, aucune policy anon/authenticated.
create table if not exists public.v51_meta_shadow_predictions (
  id bigint generated by default as identity primary key,
  race_date date not null, meeting_number integer not null, race_number integer not null,
  hippodrome text, discipline text, scheduled_start timestamptz, captured_at timestamptz not null default now(),
  minutes_to_start numeric, official_top7 integer[] not null, fundamental_top7 integer[] not null,
  shadow_top7 integer[] not null, shadow_top3 integer[] not null, consensus_count integer not null, union_count integer not null,
  consensus_confidence numeric, divergence_index numeric, stance text, swap_in integer[] not null default '{}', swap_out integer[] not null default '{}',
  runner_scores jsonb not null default '{}'::jsonb, model_name text not null default 'HorseProno_V5_1_MetaConsensus',
  status text not null default 'pending', actual_top5 integer[], shadow_hits integer, shadow_trio boolean, shadow_quarte boolean, shadow_quinte boolean,
  official_hits integer, official_quinte boolean, settled_at timestamptz, created_at timestamptz not null default now()
);
alter table public.v51_meta_shadow_predictions enable row level security;
grant select, insert, update on public.v51_meta_shadow_predictions to service_role;
grant usage, select on sequence public.v51_meta_shadow_predictions_id_seq to service_role;
